apiVersion: apps/v1
kind: Deployment
metadata:
	name: robotsevolvedbotdiscord
spec:
	selector:
		matchLabels:
			app: RobotsEvolvedDiscordbot
		replicas: 1
		template:
			metadata:
				labels:
					app: RobotsEvolvedDiscordbot
				spec:
					containers:
					- name: RobotsEvolvedDiscordbot
					  image: jtson/robotsevolvedbot:firstpush